#!/bin/bash
function check_dependencies(){
	gcc_check=$(which gcc)
	gzip_check=$(which gunzip)
	if [ -z "$gcc_check" ]
	then
		echo "Cannot find gcc in this system! Exiting"
		exit 1
	fi

	if [ -z "$gzip_check" ]
	then
		echo "Cannot find gunzip in this system! Exiting"
		exit 1
	fi
	echo "All checks passed!"
}

function compile_ubi(){
	gcc unpackbootimg_source/unpackbootimg.c -o unpackbootimg
}

function unpack_boot() {
	mkdir temp
	./unpackbootimg -i $1 -o temp
	mv temp/*.gz ramdisk.gz
	rm -rf temp/
}

function create_installer() {
	mv ramdisk installer/ramdisk-recovery.cpio
	cd installer
	zip -r installer.zip *
	cp installer.zip ../
	cd ..
}

gcc_check=$(which gcc)
if [ -z "gcc_check" ]
then
	echo "Cannot find gcc in this system, exiting!"
else
	compile_ubi
fi

unpack_boot $1
gunzip ramdisk.gz # extract ramdisk image

create_installer
